version: "3.7"

services:
  web:
    container_name: web

    environment:
      - DB_HOST=192.168.1.99
      - DB_PORT=6543
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgresdbpassword
      - DB_DATABASE=postgres_db
      - BACKEND_PORT=6544
      - NEXT_PUBLIC_BACKEND_PORT=6544

    ports:
      - 3000:3000
      - 6544:6544

    build: .
